### ISSUE TITLE
New Navy

### ISSUE THREAD

**Issue by Tao-kun** [avoid-huawei-troll/avoid-huawei-troll#8]
[孤帆远水](https://www.zhihu.com/people/gu-fan-yuan-shui/answers)

[已注销](https://www.zhihu.com/people/pingchangren/activities)

[赵丹](https://www.zhihu.com/people/huananligong/answers/by_votes)

[一条小坦坦](https://www.zhihu.com/question/344231876/answer/812921035)

**Comment by Himself65** [comment]
本人对第一位孤帆远水有点疑问
